project:
  type: website

website:
  title: "Ladenburg Consensus Statements"
  site-url: https://tscnlab.github.io/LadenburgConsensusStatements/
  repo-url: https://github.com/tscnlab/LadenburgConsensusStatements
  issue-url: https://github.com/tscnlab/LadenburgConsensusStatements/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.md
      - text: "Contributing"
        href: contributing.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/LadenburgConsensusStatements
        aria-label: Quarto GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto