project:
  type: website

website:
  title: "Light for Public Health"
  logo: assets/logo-initiative.png
  logo-alt: "Light for Public Health"
  logo-href: https://lightforpublichealth.org/
  site-url: https://lightforpublichealth.org/
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Foreword"
        href: foreword.qmd
      - text: "Background"
        href: background-information.qmd
      - text: "Consortium"
        href: consortium.qmd
      - text: "Consensus statements"
        href: consensus-statements.qmd
      - text: "Supporting organisations"
        href: supporting-orgs.qmd
      - text: "Materials"
        href: materials.qmd
      - text: "Press kit"
        href: press.qmd
      - text: "Funding"
        href: funding.qmd
      - text: "License"
        href: lic-statements.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/LadenburgConsensusStatements
        aria-label: Quarto GitHub
  page-footer:
    center: |
      [![](assets/logo-mpi.png){width=180pt}](https://www.kyb.tuebingen.mpg.de/en)
    right: "[Imprint](imprint.qmd)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

date: last-modified

language:
  title-block-published: "Last modified:"
