project:
  type: website

website:
  title: "Ladenburg Consensus Statements"
  site-url: https://lightforpublichealth.org/
  repo-url: https://github.com/tscnlab/LadenburgConsensusStatements
  issue-url: https://github.com/tscnlab/LadenburgConsensusStatements/issues
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Foreword"
        href: foreword.qmd
      - text: "Background information"
        href: background-information.qmd
      - text: "Consortium"
        href: consortium.qmd
      - text: "Consensus statements"
        href: consensus-statements.qmd
      - text: "Supporting organisations"
        href: supporting-orgs.qmd
      - text: "Funding"
        href: funding.qmd
      - text: "License"
        href: license-statements.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/LadenburgConsensusStatements
        aria-label: Quarto GitHub
  page-footer:
    center: |
      [![](assets/logo-mpi.png){width=100}](https://www.kyb.tuebingen.mpg.de/en)
    right: "[Imprint](imprint.qmd)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

date: last-modified

language:
  title-block-published: "Last modified:"
