---
title: "Background information"
title-block-banner: true
bibliography: references.bib
format:
  html:
    toc: true
    toc-location: left
    lightbox: true
---

# Background

Over the past 50 years, the knowledge of how light affects humans has changed dramatically. In addition to enabling us to perform visual tasks, navigate in the environment, and appreciate the detailed, colourful and moving visual world, light is also fundamental to our biology. The light-dark cycle synchronises our body and brain to the external world, affects the production of hormones like melatonin, and can make us more alert.

Discoveries in neurobiology identified that a special type of cell in the human eye is responsible for these circadian, neuroendocrine, and neurobehavioral effects of light. These cells, called the intrinsically photosensitive retinal ganglion cells (ipRGCs), complement the visual information captured by rods and cones. They are also different from rods and cones in the way they respond to light and have maximal sensitivity to a different part of the wavelengths underlying white light.

The characterisation of these effects of light on humans and discovery of the ipRGCs catalyzed the development of novel standards for characterising light and lighting for humans, and how they should be applied. In 2018, the International Commission on Illumination (CIE) published the International Standard CIE S 026/E:2018. In 2022, a group of international experts published consensus recommendations on the amount of light that humans should be exposed to for optimal health. Then, in 2024, the Ladenburg Roundtable “Light for health and well-being – from the biological principles to policy” was convened to discuss the application of the current knowledge to the real world – and how this translation can be supported.

This consensus document represents the coordinated effort to develop a series of core statements representing the best current scientific knowledge on the circadian, neuroendocrine, and neurobehavioral effects of light. Emerging from a White Paper developed at the Ladenburg Roundtable, this document outlines key principles for effective science and health communication. The statements form a kernel around which to build science and health communication campaigns.

It is well-known and appreciated that the translation of knowledge generated from basic research suffers a time lag from research to practice. This document is designed to accelerate the process – and make the wealth of scientific discoveries accessible to a wider audience.

# Scope

The scope of this consensus document is on the circadian, neuroendocrine, and neurobehavioral effects of visible light mediated by the eye in humans.

# Target audience

This consensus document is designed to inform a diverse range of stakeholders and multipliers who play a role in understanding, communicating, and applying knowledge about the non-visual effects of light, and who are multipliers of this knowledge. This includes public health professionals, health communication professionals, lighting industry professionals, healthcare professionals, policymakers and researchers. It is not designed to provide a definitive guide for the general public, but to support the development of public-facing messaging.

# Consensus process

A core group of experts (authors MS, LK, OS, MG, JAV, RL) led the initial development of core statements. These were then put to consensus approval by the Ladenburg Light & Health Consortium, using 75% as an approval criterion. Feedback for each statement was given and incorporated. The simplified statements and contextual information were developed once the core statements were defined, and again feedback was invited. The consensus process took place between October 2024 and February 2025.

# Structure of this document

There are 26 consensus statements approved by the entirety of Ladenburg Consortium. Each statement is supported by a simplified statement, as well as contextual information and references. In the choice of references, reviews and illustrative research articles were prioritized, and the reference is list is not to be thought of as exhaustive.

# Considerations for effective communication

To ensure purposeful and effective communication for any campaigns built on the consensus statements, multipliers should begin by clearly defining the target audience to ensure that the messaging is relevant, accessible and actionable. Language should be clear and jargon-free to reach a broad audience. Special attention should be given to reaching vulnerable and less accessible populations, including individuals with limited health literacy.
