---
title: "Consensus statements"
title-block-banner: true
bibliography: references.bib
format:
  html:
    toc: true
    toc-location: body
    toc-depth: 2
    lightbox: true
doi: 10.17617/2.3641511
---

## Light can be described by its spectrum: how much energy there is at each wavelength across the visible spectrum (from approximately 380 to 780 nm).

### Number
1

### Simplified statement
White light is made up of multiple wavelengths, which we perceive as colours.

### Contextual information
When we see different colours, we are actually seeing different wavelengths of light. Short wavelengths appear violet, while longer wavelengths appear indigo, blue, green, yellow, orange, and red.

### References
CIE. (2020). ILV: International Lighting Vocabulary. CIE Central Bureau.

Boyce, P. R. (2014). Human factors in lighting (3rd ed.). CRC Press, Taylor & Francis Group.

## The pattern of one's light exposure across the day and the year can be quite complex, and depends on where one is and what one does.

### Number
2

### Simplified statement
The amount of light around us (or the amount we are exposed to) changes as we move between indoor and outdoor spaces, throughout the day, and across seasons.

### Contextual information
Light from the sun increases from dawn to midday and decreases in the evening. Depending on location, the amount of light in the day varies greatly between summer and winter.

### References
Webler, F. S., Spitschan, M., Foster, R. G., Andersen, M., & Peirson, S. N. (2019). What is the 'spectral diet' of humans? Curr Opin Behav Sci, 30, 80-86.

## Light exposure can be described by its intensity: The total amount of energy across all wavelengths from 380 to 780 nm, weighted according to the function of interest.

### Number
3

### Simplified statement
We can measure light exposure by assessing how intense the light is at different wavelengths.

### Contextual information
We can characterise a light source by describing how much power it emits at each wavelength. This power is called intensity. Physicists measure intensity, while biological and psychological scientists study how intensity affects various processes.

### References
CIE. (2014). CIE TN 002:2014: Relating photochemical and photobiological quantities to photometric quantities. CIE Central Bureau.

## Daylight has what we call a broad spectrum, with a lot of energy across many wavelengths.

### Number
4

### Simplified statement
Daylight has a wide range of energy across multiple wavelengths – it can be separated into all the colours of the rainbow.

### Contextual information
Daylight, a combination of direct sunlight and scattered sky light, contains all visible wavelengths and more. Changes in the time of day and weather conditions shift the wavelength composition. This shift changes the colour that daylight appears.

### References
Boyce, P. R. (2014). Human factors in lighting (3rd ed.). CRC Press, Taylor & Francis Group.

## Different electric light sources (e.g., LED or fluorescent lamps, etc.) have different spectra.
### Number
5

### Simplified statement
Different light sources generate light in different ways, producing distinct wavelengths or colour.

### Contextual information
Different light source technologies use various materials to convert electricity into light. Different materials cause the intensity of light to spread across different wavelengths in different ways. This spread of light across wavelengths is known as spectral distribution.

### References
Pattison, P. M., Tsao, J. Y., Brainard, G. C., & Bugbee, B. (2018). LEDs for photons, physiology and food. Nature, 563(7732), 493-500.

DiLaura, D. L., Houser, K. W., Mistrick, R. G., & Steffy, G. R. (2011). The lighting handbook. Illuminating Engineering Society of North America.

## The properties of daylight (spectrum, intensity and spatial distribution) vary throughout the day and the year, and with changing weather.

### Number
6

### Simplified statement
The colour, intensity, and pattern of daylight change throughout the day, with seasons, and weather.

### Contextual information
As sunlight travels through the atmosphere, blue light is scattered more than other wavelengths. This makes the sky appear blue.

### References
DiLaura, D. L., Houser, K. W., Mistrick, R. G., & Steffy, G. R. (2011). The lighting handbook. Illuminating Engineering Society of North America.

Lynch, D. K., & Livingston, W. (2001). Color and light in nature (2nd ed.). Cambridge University Press.

Woelders, T., Wams, E. J., Gordijn, M. C. M., Beersma, D. G. M., & Hut, R. A. (2018). Integration of color and intensity increases time signal stability for the human circadian system when sunlight is obscured by clouds. Sci Rep, 8(1), 15214. https://doi.org/10.1038/s41598-018-33606-5

Spitschan, M., Aguirre, G. K., Brainard, D. H., & Sweeney, A. M. (2016). Variation of outdoor illumination as a function of solar elevation and light pollution. Sci Rep, 6, 26756. https://doi.org/10.1038/srep26756

## The human eye contains the retina, which has several photosensitive cells that differ in their responses to different wavelengths.

### Number
7

### Simplified statement
In the eye, the retina contains cells that allow us to detect different colours.

### Contextual information
In the human eye, the retina contains light-sensitive cells that convert light into signals for the brain. These cells are called cones, rods, and intrinsically photosensitive retinal ganglion cells (ipRGCs).

### References
Lucas, R. J., Peirson, S. N., Berson, D. M., Brown, T. M., Cooper, H. M., Czeisler, C. A., Figueiro, M. G., Gamlin, P. D., Lockley, S. W., O'Hagan, J. B., Price, L. L., Provencio, I., Skene, D. J., & Brainard, G. C. (2014). Measuring and using light in the melanopsin age. Trends Neurosci, 37(1), 1-9.

Kolb, H. (2005). Photoreceptors. In H. Kolb, E. Fernandez, B. Jones, & R. Nelson (Eds.), Webvision: The Organization of the Retina and Visual System. https://www.ncbi.nlm.nih.gov/pubmed/21413389

## The cones allow us to see colour, motion and spatial detail in bright lighting conditions.

### Number
8

### Simplified statement
Cone cells help us see colours, movement, and objects in bright light.

### Contextual information
Cones are specialized cells in the retina. They are named for their shape (how they appear under a microscope). The highest density of cones is in the fovea (in the centre of the retina).

### References
Stockman, A. (2019). Cone fundamentals and CIE standards. Current Opinion in Behavioral Sciences, 30, 87-93.

Brainard, D. H. (2019). Color, pattern, and the retinal cone mosaic. Curr Opin Behav Sci, 30, 41-47.

## The rods allow us to see rudimentary spatial detail under dim light.

### Number
9

### Simplified statement
Rod cells help us see shapes and details in dim light.

### Contextual information
Rods are highly sensitive to low light levels. They are essential for seeing at night.

### References
Fu, Y. (2018). Phototransduction in rods and cones. In H. Kolb, E. Fernandez, B. Jones, & R. Nelson (Eds.), Webvision: The Organization of the Retina and Visual System.

Kolb, H. (2009). Circuitry for rod signals through the retina. In H. Kolb, E. Fernandez, B. Jones, & R. Nelson (Eds.), Webvision: The Organization of the Retina and Visual System.

## The intrinsically photosensitive retinal ganglion cells (ipRGCs) convert light into signals that influence many physiological functions.

### Number
10

### Simplified statement
When ipRGCs detect light, they send signals to the brain to regulate various bodily functions.

### Contextual information
ipRGCs send electrical signals to brain regions that regulate sleep-wake cycles, alertness, and mood.

### References
Lucas, R. J., Peirson, S. N., Berson, D. M., Brown, T. M., Cooper, H. M., Czeisler, C. A., Figueiro, M. G., Gamlin, P. D., Lockley, S. W., O'Hagan, J. B., Price, L. L., Provencio, I., Skene, D. J., & Brainard, G. C. (2014). Measuring and using light in the melanopsin age. Trends Neurosci, 37(1), 1-9.

Spitschan, M. (2019). Melanopsin contributions to non-visual and visual function. Curr Opin Behav Sci, 30, 67-72.

Lucas, R. J., Lall, G. S., Allen, A. E., & Brown, T. M. (2012). How rod, cone, and melanopsin photoreceptors come together to enlighten the mammalian circadian clock. Prog Brain Res, 199, 1-18. https://doi.org/10.1016/B978-0-444-59427-3.00001-0

## Through the ipRGCs, light causes the suppression of melatonin in the evening and at night.

### Number
11

### Simplified statement
Light blocks the production of melatonin (a hormone that regulates sleep-wake cycles), particularly in the evening and at night.

### Contextual information
ipRGCs express melanopsin (a light-sensitive protein). When exposed to bright light, melanopsin is activated, prompting ipRGCs to transmit signals to the brain. This activation triggers a neuronal pathway, blocking the production of melatonin in the pineal gland.

### References
Brown, T. M. (2020). Melanopic illuminance defines the magnitude of human circadian light responses under a wide range of conditions. J Pineal Res, 69(1), e12655.

Prayag, A. S., Najjar, R. P., & Gronfier, C. (2019). Melatonin suppression is exquisitely sensitive to light and primarily driven by melanopsin in humans. J Pineal Res, 66(4), e12562.

Giménez MC, Stefani O, Cajochen C, Lang D, Deuring G, Schlangen LJM. Predicting melatonin suppression by light in humans: Unifying photoreceptor-based equivalent daylight illuminances, spectral composition, timing and duration of light exposure. J Pineal Res. 2022; 72:e12786. doi:

## Light is the main signal that ensures the circadian system is synchronized to the 24-hour cycles in the environment.

### Number
12

### Simplified statement
Light is the primary signal that synchronizes the body's internal clock with the sun’s day-night cycle.

### Contextual information
Light helps regulate the body's internal rhythms. This ensures biological processes start and stop at appropriate times.

### References
Blume, C., Garbazza, C., & Spitschan, M. (2019). Effects of light on human circadian rhythms, sleep and mood. Somnologie (Berl), 23(3), 147-156. https://doi.org/10.1007/s11818-019-00215-x

Duffy, J. F., & Czeisler, C. A. (2009). Effect of light on human circadian physiology. Sleep Med Clin, 4(2), 165-177.

Wright, K. P., Jr., McHill, A. W., Birks, B. R., Griffin, B. R., Rusterholz, T., & Chinoy, E. D. (2013). Entrainment of the human circadian clock to the natural light-dark cycle. Curr Biol, 23(16), 1554-1558. https://doi.org/10.1016/j.cub.2013.06.039

## Light directly influences the biological clock in the brain, regulating sleep-wake cycles and other daily physiological rhythms.

### Number
13

### Simplified statement
Light influences the body’s internal clock, which regulates sleep-wake patterns and other daily rhythms.

### Contextual information
Light exposure influences sleep, hormone release, metabolism, and alertness.

### References
Blume, C., Garbazza, C., & Spitschan, M. (2019). Effects of light on human circadian rhythms, sleep and mood. Somnologie (Berl), 23(3), 147-156. https://doi.org/10.1007/s11818-019-00215-x

Duffy, J. F., & Czeisler, C. A. (2009). Effect of light on human circadian physiology. Sleep Med Clin, 4(2), 165-177.

## Light in the morning can advance the circadian clock, and light in the evening can delay the circadian clock.

### Number
14

### Simplified statement
Morning light promotes earlier bedtime and wake time, while evening light can delay bedtime and waking.

### Contextual information
Light tells the brain to become active. Light in the morning advances the body’s internal clock (shifts it to an earlier “time”), while light in the evening delays it (shifts it to a later “time”).

### References
Khalsa, S. B., Jewett, M. E., Cajochen, C., & Czeisler, C. A. (2003). A phase response curve to single bright light pulses in human subjects. J Physiol, 549(Pt 3), 945-952.

St Hilaire, M. A., Gooley, J. J., Khalsa, S. B., Kronauer, R. E., Czeisler, C. A., & Lockley, S. W. (2012). Human phase response curve to a 1 h pulse of bright white light. J Physiol, 590(13), 3035-3045.

## Light can also boost alertness and cognitive function under some conditions.

### Number
15

### Simplified statement
In certain situations, light can improve alertness and ability to think.

### Contextual information
Under some conditions, exposure to high-intensity light during the day and night enhances alertness and improves cognitive performance.

### References
Cajochen, C., Zeitzer, J. M., Czeisler, C. A., & Dijk, D. J. (2000). Dose-response relationship for light intensity and ocular and electroencephalographic correlates of human alertness. Behav Brain Res, 115(1), 75-83. https://doi.org/10.1016/s0166-4328(00)00236-9

Lok, R., Joyce, D. S., & Zeitzer, J. M. (2022). Impact of daytime spectral tuning on cognitive function. J Photochem Photobiol B, 230, 112439.

Lok, R., Smolders, K., Beersma, D. G. M., & de Kort, Y. A. W. (2018). Light, alertness, and alerting effects of white light: a literature overview. J Biol Rhythms, 33(6), 589-601.

## What determines these physiological responses to light is primarily determined by how much light reaches the retina and stimulates the ipRGCs at a certain time.

### Number
16

### Simplified statement
The body's response to light depends on how much light and what time the light reaches the ipRGCs in the retina.

### Contextual information
The response of ipRGCs likely depends on the time of day and circadian factors.

### References
CIE. (2018). CIE S 026/E:2018: CIE system for metrology of optical Radiation for ipRGC-influenced responses to light. Central Bureau. https://doi.org/10.25039/s026.2018

Gimenez, M. C., Stefani, O., Cajochen, C., Lang, D., Deuring, G., & Schlangen, L. J. M. (2022). Predicting melatonin suppression by light in humans: Unifying photoreceptor-based equivalent daylight illuminances, spectral composition, timing and duration of light exposure. J Pineal Res, 72(2), e12786. https://doi.org/10.1111/jpi.12786

Schlangen, L. J. M., & Price, L. L. A. (2021). The lighting environment, its metrology, and non-visual responses. Front Neurol, 12, 624861.

Schollhorn, I., Stefani, O., Lucas, R. J., Spitschan, M., Epple, C., & Cajochen, C. (2024). The impact of pupil constriction on the relationship between melanopic EDI and melatonin suppression in young adult males. J Biol Rhythms, 39(3), 282-294.

## Higher light levels in the evening can increase the time to fall asleep.

### Number
17

### Simplified statement
Evening light exposure can make it harder to fall asleep.

### Contextual information
Evening light exposure tells the body it is still daytime. This increases alertness and shifts the internal clock to a later “time”.

### References
Cain, S. W., McGlashan, E. M., Vidafar, P., Mustafovska, J., Curran, S. P. N., Wang, X., Mohamed, A., Kalavally, V., & Phillips, A. J. K. (2020). Evening home lighting adversely impacts the circadian system and sleep. Sci Rep, 10(1), 19110.

Cajochen, C., Stefani, O., Schöllhorn, I., Lang, D., & Chellappa, S. L. (2022). Influence of evening light exposure on polysomnographically assessed night-time sleep: A systematic review with meta-analysis. Lighting Research & Technology, 54(6), 609-624.

Schollhorn, I., Stefani, O., Lucas, R. J., Spitschan, M., Slawik, H. C., & Cajochen, C. (2023). Melanopic irradiance defines the impact of evening display light on sleep latency, melatonin and alertness. Commun Biol, 6(1), 228.

Stefani, O., Freyburger, M., Veitz, S., Basishvili, T., Meyer, M., Weibel, J., Kobayashi, K., Shirakawa, Y., & Cajochen, C. (2021). Changing color and intensity of LED lighting across the day impacts on circadian melatonin rhythms and sleep in healthy men. J Pineal Res, 70(3), e12714. https://doi.org/10.1111/jpi.12714

## Higher light levels during the daytime can improve mood.

### Number
18

### Simplified statement
Bright light during the day can improve mood.

### Contextual information
Exposure to natural daylight (the sun) or high-intensity electric light, when free from glare, can reduce stress and improve emotional balance.

### References
Burns, A. C., Saxena, R., Vetter, C., Phillips, A. J. K., Lane, J. M., & Cain, S. W. (2021). Time spent in outdoor light is associated with mood, sleep, and circadian rhythm-related outcomes: A cross-sectional and longitudinal study in over 400,000 UK Biobank participants. J Affect Disord, 295, 347-352.

Maruani, J., & Geoffroy, P. A. (2019). Bright light as a personalized precision treatment of mood disorders. Front Psychiatry, 10, 85.

## Higher light levels during the daytime can improve sleep quality in the following night.

### Number
19

### Simplified statement
Exposure to more intense light during the day can improve sleep.

### Contextual information
Exposure to higher daytime light levels reduces sleep fragmentation (awakening throughout the night) and increases deep sleep at night.

### References
Cajochen, C., Reichert, C., Maire, M., Schlangen, L. J. M., Schmidt, C., Viola, A. U., & Gabel, V. (2019). Evidence that homeostatic sleep regulation depends on ambient lighting conditions during wakefulness. Clocks Sleep, 1(4), 517-531.

Lok, R., Woelders, T., Gordijn, M. C. M., van Koningsveld, M. J., Oberman, K., Fuhler, S. G., Beersma, D. G. M., & Hut, R. A. (2022). Bright light during wakefulness improves sleep quality in healthy men: a forced desynchrony study under dim and bright light (III). J Biol Rhythms, 37(4), 429-441.

Wams, E. J., Woelders, T., Marring, I., van Rosmalen, L., Beersma, D. G. M., Gordijn, M. C. M., & Hut, R. A. (2017). Linking light exposure and subsequent sleep: a field polysomnography study in humans. Sleep, 40(12).

## Following a medically-prescribed protocol for bright light, exposure in the morning can lead to improvements in mood for people with certain clinical diagnoses.

### Number
20

### Simplified statement
Doctors may prescribe light therapy as treatment for winter depression and other health conditions.

### Contextual information
Exposure to bright light has been shown to improve depressive symptoms in individuals with Seasonal Affective Disorder.

### References
Meesters, Y., & Gordijn, M. C. (2016). Seasonal affective disorder, winter type: current insights and treatment options. Psychol Res Behav Manag, 9, 317-327.

Terman, M., Terman, J. S., Quitkin, F. M., McGrath, P. J., Stewart, J. W., & Rafferty, B. (1989). Light therapy for seasonal affective disorder. A review of efficacy. Neuropsychopharmacology, 2(1), 1-22.

## A healthy pattern of daily light exposure includes a rhythm of bright light and darkness every day.

### Number
21

### Simplified statement
A healthy daily routine includes bright light during the day and darkness at night.

### Contextual information
Maintaining a regular pattern of bright light during the day and darkness at night is associated with better physical and mental health.

### References

Brown, T. M., Brainard, G. C., Cajochen, C., Czeisler, C. A., Hanifin, J. P., Lockley, S. W., Lucas, R. J., Munch, M., O'Hagan, J. B., Peirson, S. N., Price, L. L. A., Roenneberg, T., Schlangen, L. J. M., Skene, D. J., Spitschan, M., Vetter, C., Zee, P. C., & Wright, K. P., Jr. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure to best support physiology, sleep, and wakefulness in healthy adults. PLoS Biol, 20(3), e3001571.

Burns, A. C., Windred, D. P., Rutter, M. K., Olivier, P., Vetter, C., Saxena, R., Lane, J. M., Phillips, A. J. K., & Cain, S. W. (2023). Day and night light exposure are associated with psychiatric disorders: an objective light study in >85,000 people. Nature Mental Health, 1(11), 853-862.

Windred, D. P., Burns, A. C., Lane, J. M., Olivier, P., Rutter, M. K., Saxena, R., Phillips, A. J. K., & Cain, S. W. (2024). Brighter nights and darker days predict higher mortality risk: A prospective analysis of personal light exposure in >88,000 individuals. Proc Natl Acad Sci U S A, 121(43), e2405924121.
Windred, D. P., Burns, A. C., Rutter, M. K., Ching Yeung, C. H., Lane, J. M., Xiao, Q., Saxena, R., Cain, S. W., & Phillips, A. J. K. (2024). Personal light exposure patterns and incidence of type 2 diabetes: analysis of 13 million hours of light sensor data and 670,000 person-years of prospective observation. Lancet Reg Health Eur, 42, 100943.

## Age can influence the physiological effect of light on humans, as less light reaches the retina because of ageing.

### Number
22

### Simplified statement
As people age, the lenses of the eye can become less transparent, which may reduce the effects of light on the internal clock and sleep.

### Contextual information
With age, the eye’s lenses become less transparent, which may reduce the body’s response to light exposure.

### References
Chellappa, S. L., Bromundt, V., Frey, S., & Cajochen, C. (2021). Age-related neuroendocrine and alerting responses to light. Geroscience, 43(4), 1767-1781.

Gimenez, M. C., Kanis, M. J., Beersma, D. G., van der Pol, B. A., van Norren, D., & Gordijn, M. C. (2010). In vivo quantification of the retinal reflectance spectral composition in elderly subjects before and after cataract surgery: Implications for the non-visual effects of light. J Biol Rhythms, 25(2), 123-131.

Mellerio, J. (1987). Yellowing of the human lens: nuclear and cortical contributions. Vision Res.  27(9), 1581-1587. https://doi.org/10.1016/0042-6989(87)90166-0

Najjar, R. P., Chiquet, C., Teikari, P., Cornut, P. L., Claustrat, B., Denis, P., Cooper, H. M., & Gronfier, C. (2014). Aging of non-visual spectral sensitivity to light in humans: compensatory mechanisms? PLoS One, 9(1), e85837.

## There are substantial individual differences in the physiological response to light.

### Number
23

### Simplified statement
How people respond to light can vary greatly.

### Contextual information
Individual differences in light sensitivity are influenced by factors such as age, genetics, and behavior.

### References
Chellappa, S. L. (2021). Individual differences in light sensitivity affect sleep and circadian rhythms. Sleep, 44(2).

Phillips, A. J. K., Vidafar, P., Burns, A. C., McGlashan, E. M., Anderson, C., Rajaratnam, S. M. W., Lockley, S. W., & Cain, S. W. (2019). High sensitivity and interindividual variability in the response of the human circadian system to evening light. Proc Natl Acad Sci U S A, 116(24), 12019-12024.

## The majority of studies on the physiological effects of light have been performed in the laboratory.

### Number
24

### Simplified statement
Most research on light’s effects on the body has been conducted in the laboratory.

### Contextual information
Studies investigating light exposure in the real-world are needed.

### References
Spitschan, M., & Joyce, D. S. (2023). Human-Centric Lighting Research and Policy in the Melanopsin Age. Policy Insights Behav Brain Sci, 10(2), 237-246.

## There is a need for studies on the physiological effects of light incorporating a broad range of study populations.

### Number
25

### Simplified statement
More studies are needed to understand how light influences health in different groups of people.

### Contextual information
Most studies on the physiological effects of light have focused on limited populations (specific age groups, ethnicities, or health conditions). It is important that future research studies more diverse populations over wider geographical regions.

### References
Johnson, D. A., Wallace, D. A., & Ward, L. (2024). Racial/ethnic and sex differences in the association between light at night and actigraphy-measured sleep duration in adults: NHANES 2011-2014. Sleep Health, 10(1S), S184-S190.

Spitschan, M., & Santhi, N. (2022). Individual differences and diversity in human physiological responses to light. EBioMedicine, 75, 103640.

## The physiological effects of light are an area of active investigation.

### Number
26

### Simplified statement
Scientists continue to explore how light affects bodily functions and overall health.

### Contextual information
Scientific and popular interest in the effects of light on biological rhythms, sleep, alertness, mood, and health is growing. Technological and scientific advances are enabling researchers to more precisely study different wavelengths and different intensities.

### References
CIE. (2024). CIE PS 001:2024 CIE Position Statement on Integrative Lighting – Recommending Proper Light at the Proper Time, 3rd Edition. CIE Central Bureau.
