---
title: "Funding"
---

The Ladenburg Roundtable “Light for health and well-being – from the biological principles to policy” (14-16 April 2024) was supported by the Daimler and Benz Foundation. The funders had no role in the content, decision to publish, or preparation of the statements.

Foreword

For centuries, we thought we understood how the human eye works — until a surprising discovery in the 1990s changed everything. The clue came from a domain quite different from ophthalmology, the medical discipline specialised in the eye. In a strain of mice lacking rod or cone photoreceptors (the retinal cells responsible for colour and light sensitivity), exposure to light affected their behavioural circadian rhythms. The biological clock in these mice was still synchronised by light to the 24-hour day-night cycle even though they were blind with respect to vision. Could there be a third, undiscovered type of photoreceptor present in the retina? The next chapter in this quest was when the intrinsically photosensitive retinal ganglion cells (ipRGCs) were revealed to be the mysterious photoreceptors. Together with rod and cone inputs, they signal a wide range of light levels in the environment, from the dim glow of starlight to the brightness of the midday sun. Their photopigment is melanopsin, with peak sensitivity in the short-wavelength part of the spectrum. Nerve pathways from the ipRGCs to the brain are amazingly diverse, showing that light plays an important role in regulating hormone secretion, sleep regulation, rhythms in body temperature, cognition, mood and alertness, and circadian and seasonal timing.

That is the basic science. Only recognised around two decades ago, these ipRGCs have enormously changed our understanding of the importance of light for health and well-being. But even before scientists uncovered this mechanism, bright light was already being used to treat depressive mood in people with seasonal affective disorder.

Not surprisingly, the discovery of the ipRGCs introduced a new dimension for crafting and optimising light in the built environment: not only to maximise visual functions and minimise energy use, but also to maintain simultaneous input to the ipRGCs at the right level at the right time. It completely changed the field, leading to the development and publication of a melanopsin-based standard metrology system for quantifying the effects of light on humans by the International Commission on Illumination (CIE) in 2018.

Light and lighting have become a public health issue, and everyone should know about these remarkable findings. Simply paying attention to one’s personal light exposure — getting outside in the morning and dimming screens before bed — can make a big difference in how we feel and sleep.

Anna Wirz-Justice PhD

Professor Emerita
Centre for Chronobiology, University Psychiatric Clinics Basel, Switzerland